plugins {
    id "java-library"
    id "maven-publish"
    id "net.neoforged.gradle.userdev" version "7.1.36"
}

apply from: file("common.gradle")

sourceSets {
    main.java {
        srcDirs += "Forge/main/java"
        srcDirs += "libs/Noise2D/src/main/java"
        srcDirs += "libs/Cereal/src/main/java"
        exclude "com/terraforged/mod/hooks/BuiltinHook.java"
        exclude "com/terraforged/mod/mixin/client/MixinWorldGenSettingsComponent.java"
        exclude "com/terraforged/mod/mixin/common/MixinPackRepository.java"
        exclude "com/terraforged/mod/mixin/common/MixinRegistryAccess.java"
        exclude "com/terraforged/mod/mixin/common/MixinRegistryOps.java"
    }
    main.resources {
        srcDirs += "Forge/main/resources"
        srcDirs += "generated/resources"
    }
}

repositories {
    maven { url "https://repo.spongepowered.org/maven" }
    flatDir { dirs "lib" }
}

base {
    archivesName = "${archives_base_name}-${minecraft_version}"
}

runs {
    configureEach {
        systemProperty "forge.logging.markers", "REGISTRIES"
        systemProperty "forge.logging.console.level", "debug"
        systemProperty "mixin.env.remapRefMap", "true"
        systemProperty "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"

        argument "-mixin.config=terraforged.mixins.json"
        jvmArgument "-Ddev"

        workingDirectory project.layout.projectDirectory.dir("run").dir(name)
        modSource project.sourceSets.main
    }

    client {
        systemProperty "neoforge.enabledGameTestNamespaces", mod_id
    }

    server {
        systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        argument "--nogui"
    }

    data {
        jvmArgument "-Ddatagen"
        arguments.addAll "--mod", mod_id, "--all", "--output", file("generated/resources/").absolutePath, "--existing", file("src/main/resources/").absolutePath
    }
}

configurations {
    localRuntime
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.named("jar", Jar).configure {
    manifest {
        attributes(["MixinConfigs": "terraforged.mixins.json"])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(["META-INF/neoforge.mods.toml"]) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.withType(Test).configureEach {
    failOnNoDiscoveredTests = false
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
